# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(unique=True, verbose_name='顺序')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('time_limit', models.IntegerField(help_text='单位为 s', verbose_name='时间限制')),
                ('momery_limit', models.IntegerField(help_text='单位为 KB', verbose_name='内存限制')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '问题',
                'verbose_name_plural': '问题',
                'ordering': ['order'],
            },
        ),
    ]
