# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-15 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': '拥有该邮箱的用户已存在。'}, max_length=254, unique=True, verbose_name='邮箱'),
        ),
    ]
