# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='momery_limit',
            new_name='memory_limit',
        ),
    ]
