# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-15 10:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170815_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('C', 'C'), ('CPP', 'C++')], max_length=5, verbose_name='语言')),
                ('code', models.TextField(verbose_name='代码')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submit_set', to='main.Problem', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submit_set', to=settings.AUTH_USER_MODEL, verbose_name='提交者')),
            ],
            options={
                'verbose_name': '提交',
                'verbose_name_plural': '提交',
            },
        ),
    ]
