# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170331_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['order'], 'verbose_name': '题目', 'verbose_name_plural': '题目'},
        ),
        migrations.AddField(
            model_name='problem',
            name='contributor',
            field=models.TextField(blank=True, verbose_name='题目贡献者'),
        ),
        migrations.AddField(
            model_name='problem',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='过期的提交，计算成绩时会打折扣。', verbose_name='截止日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='desc',
            field=models.TextField(default='', verbose_name='题目描述'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='hint',
            field=models.TextField(blank=True, verbose_name='提示'),
        ),
        migrations.AddField(
            model_name='problem',
            name='input_desc',
            field=models.TextField(blank=True, verbose_name='输入描述'),
        ),
        migrations.AddField(
            model_name='problem',
            name='input_sample',
            field=models.TextField(blank=True, verbose_name='输入样例'),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_desc',
            field=models.TextField(blank=True, verbose_name='输出描述'),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_sample',
            field=models.TextField(blank=True, verbose_name='输出样例'),
        ),
        migrations.AddField(
            model_name='problem',
            name='released',
            field=models.BooleanField(default=False, help_text='普通学生账号只能看到已发布的题目。', verbose_name='是否已发布'),
        ),
        migrations.AddField(
            model_name='problem',
            name='sample_num',
            field=models.PositiveIntegerField(default=0, verbose_name='测试数据总数'),
            preserve_default=False,
        ),
    ]
