# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-17 11:00
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='题目描述'),
        ),
    ]
