# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-17 11:43
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170817_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='contributor',
            field=models.CharField(blank=True, max_length=40, verbose_name='题目贡献者'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='hint',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='提示'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='input_desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='输入描述'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='output_desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='输出描述'),
        ),
    ]
