# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-17 11:58
from __future__ import unicode_literals

from django.db import migrations


def create_groups(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Group = apps.get_model("auth", "Group")
    db_alias = schema_editor.connection.alias
    Group.objects.using(db_alias).create(
        name="faculty",
    )


def delete_groups(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    Group = apps.get_model("auth", "Group")
    db_alias = schema_editor.connection.alias
    group_1 = Group.objects.using(db_alias).get(name="faculty")
    group_1.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170817_1953'),
    ]

    operations = [
        migrations.RunPython(create_groups, delete_groups),
    ]
