# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-20 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170817_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='顺序')),
                ('input_file', models.FileField(upload_to='uploads/', verbose_name='输入文件')),
                ('output_file', models.FileField(upload_to='uploads/', verbose_name='输出文件')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': '测试数据',
                'verbose_name_plural': '测试数据',
            },
        ),
        migrations.RemoveField(
            model_name='problem',
            name='sample_num',
        ),
        migrations.AddField(
            model_name='testdata',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testdata_set', to='main.Problem', verbose_name='题目'),
        ),
    ]
