# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-20 15:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20170820_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='compile_status',
            field=models.CharField(blank=True, choices=[('O', '编译成功'), ('E', '编译失败')], max_length=1, verbose_name='编译状态'),
        ),
        migrations.AddField(
            model_name='submit',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='错误消息'),
        ),
        migrations.AddField(
            model_name='submit',
            name='judge_status',
            field=models.CharField(choices=[('P', '等待中'), ('J', '判题中'), ('C', '已完成判题')], default='P', max_length=1, verbose_name='判题状态'),
        ),
        migrations.AddField(
            model_name='submit',
            name='run_results',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='[(status, time, memory)...], time in ms, memory in KB.', null=True, verbose_name='运行结果'),
        ),
        migrations.AddField(
            model_name='submit',
            name='score',
            field=models.FloatField(blank=True, help_text='得分使用 100 分制', null=True, verbose_name='得分'),
        ),
    ]
