# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-21 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20170821_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submit',
            options={'ordering': ['-id'], 'verbose_name': '提交', 'verbose_name_plural': '提交'},
        ),
        migrations.AlterField(
            model_name='problem',
            name='released',
            field=models.BooleanField(db_index=True, default=False, help_text='普通学生账号只能看到已发布的题目。', verbose_name='是否已发布'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='judge_status',
            field=models.CharField(choices=[('P', '等待中'), ('J', '判题中'), ('C', '已完成判题')], db_index=True, default='P', max_length=1, verbose_name='判题状态'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='score',
            field=models.FloatField(blank=True, db_index=True, help_text='得分使用 100 分制', null=True, verbose_name='得分'),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='order',
            field=models.PositiveIntegerField(db_index=True, verbose_name='顺序'),
        ),
    ]
