# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-21 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20170821_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='language',
            field=models.CharField(choices=[('C89', 'C89'), ('C99', 'C99'), ('C11', 'C11'), ('C++03', 'C++03'), ('C++11', 'C++11')], max_length=5, verbose_name='语言'),
        ),
    ]
