# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-21 10:01
from __future__ import unicode_literals

from django.db import migrations


def upgrade_lang(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Submit = apps.get_model("main", "Submit")
    db_alias = schema_editor.connection.alias
    for submit in Submit.objects.all():
        if submit.language == 'CPP':
            submit.language = 'C++11'
        else:
            submit.language = 'C99'
        submit.save()


def downgrade_lang(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    Submit = apps.get_model("main", "Submit")
    db_alias = schema_editor.connection.alias
    for submit in Submit.objects.all():
        if submit.language in ['C++03', 'C++11']:
            submit.language = 'CPP'
        else:
            submit.language = 'C'
        submit.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20170821_1800'),
    ]

    operations = [
        migrations.RunPython(upgrade_lang, downgrade_lang),
    ]
