# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-10 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20170821_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='compare_file',
            field=models.FileField(blank=True, upload_to='uploads/judge/', verbose_name='Compare 函数文件'),
        ),
    ]
