# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-10 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import main.utils.compare_utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_problem_compare_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='compare_file',
            field=models.FileField(blank=True, upload_to='uploads/judge/', validators=[main.utils.compare_utils.validate_compare_file], verbose_name='Compare 函数文件'),
        ),
    ]
