# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-10 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import main.utils.compare_utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20170910_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='compare_file',
            field=models.FileField(blank=True, help_text='请实现 compare_func 以自定义比较函数，例：def compare_func(answer, output): return True', upload_to='uploads/judge/', validators=[main.utils.compare_utils.validate_compare_file], verbose_name='Compare 函数文件'),
        ),
    ]
