# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-10 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20170910_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='judge_status',
            field=models.CharField(choices=[('P', '等待中'), ('J', '判题中'), ('C', '已完成判题'), ('C', '判题失败')], db_index=True, default='P', max_length=1, verbose_name='判题状态'),
        ),
    ]
