# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-11 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20170910_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': '拥有该邮箱的用户已存在。'}, max_length=254, null=True, unique=True, verbose_name='邮箱'),
        ),
    ]
