# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-11 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20170911_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='judge_status',
            field=models.CharField(choices=[('P', '等待中'), ('J', '判题中'), ('C', '已完成判题'), ('F', '判题失败')], db_index=True, default='P', max_length=1, verbose_name='判题状态'),
        ),
    ]
