# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-24 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20170917_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='使用该字段标记删除，禁止物理删除。', verbose_name='是否已删除'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='released',
            field=models.BooleanField(default=False, help_text='普通学生账号只能看到已发布的题目。', verbose_name='是否已发布'),
        ),
    ]
