# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-24 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20170924_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='使用该字段标记删除。', verbose_name='禁用'),
        ),
    ]
