# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-24 05:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20170924_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='number',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999999)], verbose_name='题目编号'),
        ),
    ]
